// CSV Field Headers and Mappings

export const STUDENT_CSV_HEADERS = [
  'id',
  'name',
  'email',
  'rollNumber',
  'school',
  'department',
  'specialization',
  'year',
  'semester',
  'cgpa',
  'phone',
  'dateOfBirth',
  'gender',
  'address.street',
  'address.city',
  'address.state',
  'address.pincode',
  'parentDetails.fatherName',
  'parentDetails.motherName',
  'parentDetails.fatherOccupation',
  'parentDetails.motherOccupation',
  'parentDetails.annualIncome',
  'parentDetails.contactNumber',
  'academicHistory.tenth.board',
  'academicHistory.tenth.year',
  'academicHistory.tenth.percentage',
  'academicHistory.twelfth.board',
  'academicHistory.twelfth.year',
  'academicHistory.twelfth.percentage',
  'academicHistory.twelfth.stream',
  'skills.technical',
  'skills.soft',
  'skills.certifications',
  'skills.languages',
  'placementStatus.isRegistered',
  'placementStatus.preferredLocations',
  'placementStatus.expectedSalary.min',
  'placementStatus.expectedSalary.max',
  'isActive',
  'lastLoginDate',
  'createdAt',
  'updatedAt'
];

export const FACULTY_CSV_HEADERS = [
  'id',
  'name',
  'email',
  'employeeId',
  'designation',
  'school',
  'department',
  'specialization',
  'experience',
  'qualification',
  'phone',
  'dateOfJoining',
  'dateOfBirth',
  'gender',
  'address.street',
  'address.city',
  'address.state',
  'address.pincode',
  'academicBackground.phd.university',
  'academicBackground.phd.year',
  'academicBackground.phd.thesis',
  'academicBackground.masters.degree',
  'academicBackground.masters.university',
  'academicBackground.masters.year',
  'academicBackground.bachelors.degree',
  'academicBackground.bachelors.university',
  'academicBackground.bachelors.year',
  'researchInterests',
  'mentorship.phdStudents',
  'mentorship.mastersStudents',
  'mentorship.undergraduateProjects',
  'isActive',
  'lastLoginDate',
  'createdAt',
  'updatedAt'
];

export const OPERATIONS_CSV_HEADERS = [
  'id',
  'name',
  'email',
  'employeeId',
  'designation',
  'department',
  'experience',
  'phone',
  'dateOfJoining',
  'dateOfBirth',
  'gender',
  'address.street',
  'address.city',
  'address.state',
  'address.pincode',
  'responsibilities',
  'skills',
  'performanceMetrics.applicationsProcessed',
  'performanceMetrics.interviewsCoordinated',
  'performanceMetrics.placementSuccess',
  'performanceMetrics.studentSatisfaction',
  'isActive',
  'lastLoginDate',
  'createdAt',
  'updatedAt'
];

export const OUTREACH_CSV_HEADERS = [
  'id',
  'name',
  'email',
  'employeeId',
  'designation',
  'department',
  'experience',
  'phone',
  'dateOfJoining',
  'dateOfBirth',
  'gender',
  'address.street',
  'address.city',
  'address.state',
  'address.pincode',
  'responsibilities',
  'skills',
  'companiesManaged',
  'performanceMetrics.companiesOnboarded',
  'performanceMetrics.jobsPosted',
  'performanceMetrics.placementSuccess',
  'performanceMetrics.relationshipScore',
  'isActive',
  'lastLoginDate',
  'createdAt',
  'updatedAt'
];

export const ADMIN_CSV_HEADERS = [
  'id',
  'name',
  'email',
  'employeeId',
  'designation',
  'department',
  'experience',
  'phone',
  'dateOfJoining',
  'dateOfBirth',
  'gender',
  'address.street',
  'address.city',
  'address.state',
  'address.pincode',
  'responsibilities',
  'skills',
  'systemAccess',
  'managementAreas',
  'performanceMetrics.systemUptime',
  'performanceMetrics.userSatisfaction',
  'performanceMetrics.dataAccuracy',
  'performanceMetrics.processEfficiency',
  'isActive',
  'lastLoginDate',
  'createdAt',
  'updatedAt'
];

// CSV Configuration
export const CSV_CONFIG = {
  encoding: 'utf-8',
  delimiter: ',',
  quote: '"',
  escape: '"',
  lineBreak: '\n',
  bom: true // Byte Order Mark for Excel compatibility
};

// Data Type Mappings
export const DATA_TYPE_HEADERS = {
  students: STUDENT_CSV_HEADERS,
  faculty: FACULTY_CSV_HEADERS,
  operations: OPERATIONS_CSV_HEADERS,
  outreach: OUTREACH_CSV_HEADERS,
  admin: ADMIN_CSV_HEADERS
};

// Field Display Names for Headers
export const FIELD_DISPLAY_NAMES: Record<string, string> = {
  'id': 'ID',
  'name': 'Full Name',
  'email': 'Email Address',
  'rollNumber': 'Roll Number',
  'employeeId': 'Employee ID',
  'school': 'School',
  'department': 'Department',
  'specialization': 'Specialization',
  'year': 'Academic Year',
  'semester': 'Current Semester',
  'cgpa': 'CGPA',
  'phone': 'Phone Number',
  'dateOfBirth': 'Date of Birth',
  'gender': 'Gender',
  'address.street': 'Street Address',
  'address.city': 'City',
  'address.state': 'State',
  'address.pincode': 'PIN Code',
  'parentDetails.fatherName': 'Father Name',
  'parentDetails.motherName': 'Mother Name',
  'parentDetails.fatherOccupation': 'Father Occupation',
  'parentDetails.motherOccupation': 'Mother Occupation',
  'parentDetails.annualIncome': 'Annual Income',
  'parentDetails.contactNumber': 'Parent Contact',
  'academicHistory.tenth.board': '10th Board',
  'academicHistory.tenth.year': '10th Year',
  'academicHistory.tenth.percentage': '10th Percentage',
  'academicHistory.twelfth.board': '12th Board',
  'academicHistory.twelfth.year': '12th Year',
  'academicHistory.twelfth.percentage': '12th Percentage',
  'academicHistory.twelfth.stream': '12th Stream',
  'skills.technical': 'Technical Skills',
  'skills.soft': 'Soft Skills',
  'skills.certifications': 'Certifications',
  'skills.languages': 'Languages',
  'placementStatus.isRegistered': 'Placement Registered',
  'placementStatus.preferredLocations': 'Preferred Locations',
  'placementStatus.expectedSalary.min': 'Expected Salary Min',
  'placementStatus.expectedSalary.max': 'Expected Salary Max',
  'designation': 'Designation',
  'experience': 'Experience (Years)',
  'qualification': 'Qualification',
  'dateOfJoining': 'Date of Joining',
  'academicBackground.phd.university': 'PhD University',
  'academicBackground.phd.year': 'PhD Year',
  'academicBackground.phd.thesis': 'PhD Thesis',
  'academicBackground.masters.degree': 'Masters Degree',
  'academicBackground.masters.university': 'Masters University',
  'academicBackground.masters.year': 'Masters Year',
  'academicBackground.bachelors.degree': 'Bachelors Degree',
  'academicBackground.bachelors.university': 'Bachelors University',
  'academicBackground.bachelors.year': 'Bachelors Year',
  'researchInterests': 'Research Interests',
  'mentorship.phdStudents': 'PhD Students',
  'mentorship.mastersStudents': 'Masters Students',
  'mentorship.undergraduateProjects': 'UG Projects',
  'responsibilities': 'Responsibilities',
  'skills': 'Skills',
  'companiesManaged': 'Companies Managed',
  'systemAccess': 'System Access',
  'managementAreas': 'Management Areas',
  'performanceMetrics.applicationsProcessed': 'Applications Processed',
  'performanceMetrics.interviewsCoordinated': 'Interviews Coordinated',
  'performanceMetrics.placementSuccess': 'Placement Success %',
  'performanceMetrics.studentSatisfaction': 'Student Satisfaction',
  'performanceMetrics.companiesOnboarded': 'Companies Onboarded',
  'performanceMetrics.jobsPosted': 'Jobs Posted',
  'performanceMetrics.relationshipScore': 'Relationship Score',
  'performanceMetrics.systemUptime': 'System Uptime %',
  'performanceMetrics.userSatisfaction': 'User Satisfaction',
  'performanceMetrics.dataAccuracy': 'Data Accuracy %',
  'performanceMetrics.processEfficiency': 'Process Efficiency %',
  'isActive': 'Active Status',
  'lastLoginDate': 'Last Login',
  'createdAt': 'Created Date',
  'updatedAt': 'Updated Date'
};

// Required Fields for Each Data Type
export const REQUIRED_FIELDS = {
  students: ['name', 'email', 'rollNumber', 'school', 'department', 'year', 'semester'],
  faculty: ['name', 'email', 'employeeId', 'designation', 'school', 'department'],
  operations: ['name', 'email', 'employeeId', 'designation', 'department'],
  outreach: ['name', 'email', 'employeeId', 'designation', 'department'],
  admin: ['name', 'email', 'employeeId', 'designation', 'department']
};

// Validation Rules
export const VALIDATION_RULES = {
  email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  phone: /^[\+]?[1-9][\d]{0,15}$/,
  cgpa: { min: 0, max: 10 },
  percentage: { min: 0, max: 100 },
  year: { min: 1, max: 5 },
  semester: { min: 1, max: 10 },
  experience: { min: 0, max: 50 },
  annualIncome: { min: 0, max: 10000000 }
};